apiVersion: apps/v1
kind: Deployment
metadata:
 name: mavenwebapplication
 namespace: qa-ns
spec:
 replicas: 2
 selector:
  matchLabels:
   app: mavenwebapplication
 template:
  metadata: 
   labels:
    app: mavenwebapplication
  spec:
    containers:
    - name: maven-web-application  
      image: amitdocker786/maven-web-application:TAG
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: mavenwebapplication
 namespace: qa-ns
spec:
 selector:
  app: mavenwebapplication
 type: NodePort
 ports: 
 - port: 80
   targetPort: 8080
